FROM node:lts-alpine3.10 AS BUILD-stage

WORKDIR /var/app/client

COPY ./package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM nginx:alpine AS DEPLOY-stage

COPY --from=BUILD-stage /var/app/client/dist /usr/share/nginx/html

EXPOSE 80