server:
  port: ${PORT}
  ssl:
    certificate-private-key: ${CERTIFICATE-PRIVATE-KEY}
    certificate: ${CERTIFICATE}
    enabled: ${SSL_ENABLED}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true

influx:
  test-user-username: ${TEST_USER_USERNAME}
  test-user-email: ${TEST_USER_EMAIL}
  test-admin-username: ${ADMIN_USER_USERNAME}
  test-admin-email: ${ADMIN_USER_EMAIL}
  test-password: ${TEST_USER_PASSWORD}
  jwt-secret-key: ${JWT_SECURITY_KEY}
  jwt-token-expiry-ms: ${JWT_TOKEN_EXPIRY_MS}
