server:
  port: 8080

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      format-sql: true

influx:
  test-user-username: ${testUserUsername}
  test-user-email: ${testUserEmail}
  test-admin-username: ${testAdminUsername}
  test-admin-email: ${testAdminEmail}
  test-password: ${testPassword}
